name: buildx

on:
  push:
    branches: main

jobs:
  buildx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          cat <<'EOF' > docker-bake.hcl
          group "default" {
              targets = [
                  "php",
                  "php-fpm",
                  "php-cli",
              ]
          }

          target "default" {
              context="."
              platforms = [
                  "linux/amd64",
                  "linux/arm64"
              ]
          }

          target "php" {
              inherits=["default"]
              dockerfile="php/Dockerfile"
              tags = [
                  "16nsk/php:latest",
              ]
          }

          target "php-fpm" {
              inherits=["default"]
              dockerfile="php/Dockerfile.fpm"
              tags = [
                  "16nsk/php:fpm",
              ]
          }

          target "php-cli" {
              inherits=["default"]
              dockerfile="php/Dockerfile.cli"
              tags = [
                  "16nsk/php:cli",
              ]
          }
          EOF
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          files: docker-bake.hcl
